name = "Modern Automation Expert"
author = "pen787"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1aee64bbf3b624fd5b9c8cc00241b53bb93e7c7ae970b68228309107369da597"

[versions]
fabric = "0.14.20"
minecraft = "1.19.2"
