name = "Modern Automation Expert"
author = "pen787"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "90e37203499f2a3568c270b226cebc16af2e6240a0fe36c7c67e10a5c53de1bd"

[versions]
fabric = "0.14.20"
minecraft = "1.19.2"
