name = "Modern Automation Expert"
author = "pen787"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9e40f6c75fff88dcb7db6be69e613b8c540191e49d17d8c976cb4f2ad9ae0d0e"

[versions]
fabric = "0.14.20"
minecraft = "1.19.2"
