# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				panda = true
				bee = true
				axolotl = true
				egg = true
				arrow = true
				cow = true
				pig = true
				allay = true
				skeleton = true
				llama = true
				bat = true
				rabbit = true
				drowned = true
				experience_orb = true
				dolphin = true
				item = true
				stray = true
				turtle = true
				salmon = true
				wandering_trader = true
				goat = true
				ocelot = true
				horse = true
				phantom = true
				llama_spit = true
				mooshroom = true
				glow_squid = true
				glow_item_frame = false
				squid = true
				parrot = true
				creeper = true
				lightning_bolt = true
				enderman = true
				chicken = true
				trader_llama = true
				donkey = true
				chest_minecart = true
				tropical_fish = true
				fox = true
				slime = true
				pillager = true
				iron_golem = true
				cat = true
				zombie = true
				sheep = true
				player = true
				pufferfish = true
				wolf = true
				villager = true
				skeleton_horse = true
				zombie_villager = true
				elder_guardian = true
				strider = true
				polar_bear = true
				cave_spider = true
				cod = true
				witch = true
				spider = true

			[light_sources.settings.entities.create]
				stationary_contraption = true
				super_glue = true

			[light_sources.settings.entities.another_furniture]
				seat = true

			[light_sources.settings.entities.artifacts]
				mimic = true

			[light_sources.settings.entities.ad_astra]
				ice_spit = true
				tier_1_rocket = true
				corrupted_lunarian = true
				lunarian = true
				star_crawler = true
				tier_1_rover = true
				lander = true

